// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const AGGREGATE_COMMENT = gql`
  query AggregateComment($filter: CommentFilter) {
    aggregateComment(filter: $filter) {
      count
      textMin
      textMax
      created_atMin
      created_atMax
    }
  }
`;
