// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const GET_COMMENT = gql`
  query GetComment($id: ID!) {
    getComment(id: $id) {
      id
      creator {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      text
      parentProblem {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      created_at
      associatedStatus
      userTags {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      repliesAggregate {
        count
        textMin
        textMax
        created_atMin
        created_atMax
      }
      userTagsAggregate {
        count
        nameMin
        nameMax
        githubMin
        githubMax
        emailMin
        emailMax
        telegramMin
        telegramMax
        rateMin
        rateMax
        rateSum
        rateAvg
      }
    }
  }
`;
