// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const QUERY_COMMENT = gql`
  query QueryComment(
    $filter: CommentFilter
    $order: CommentOrder
    $first: Int
    $offset: Int
  ) {
    queryComment(
      filter: $filter
      order: $order
      first: $first
      offset: $offset
    ) {
      id
      creator {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      text
      parentProblem {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      created_at
      associatedStatus
      userTags {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      repliesAggregate {
        count
        textMin
        textMax
        created_atMin
        created_atMax
      }
      userTagsAggregate {
        count
        nameMin
        nameMax
        githubMin
        githubMax
        emailMin
        emailMax
        telegramMin
        telegramMax
        rateMin
        rateMax
        rateSum
        rateAvg
      }
    }
  }
`;
