// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const AGGREGATE_ORGANIZATION = gql`
  query AggregateOrganization($filter: OrganizationFilter) {
    aggregateOrganization(filter: $filter) {
      count
      nameMin
      nameMax
      githubOrgMin
      githubOrgMax
    }
  }
`;
