// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const GET_ORGANIZATION = gql`
  query GetOrganization($name: String!) {
    getOrganization(name: $name) {
      name
      githubOrg
      admins {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      createdBy {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      maintainers {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      contributors {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      problems {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      adminsAggregate {
        count
        nameMin
        nameMax
        githubMin
        githubMax
        emailMin
        emailMax
        telegramMin
        telegramMax
        rateMin
        rateMax
        rateSum
        rateAvg
      }
      maintainersAggregate {
        count
        nameMin
        nameMax
        githubMin
        githubMax
        emailMin
        emailMax
        telegramMin
        telegramMax
        rateMin
        rateMax
        rateSum
        rateAvg
      }
      contributorsAggregate {
        count
        nameMin
        nameMax
        githubMin
        githubMax
        emailMin
        emailMax
        telegramMin
        telegramMax
        rateMin
        rateMax
        rateSum
        rateAvg
      }
      problemsAggregate {
        count
        titleMin
        titleMax
        shortDescriptionMin
        shortDescriptionMax
        detailedDescriptionMin
        detailedDescriptionMax
        claimedAtMin
        claimedAtMax
        created_atMin
        created_atMax
        updated_atMin
        updated_atMax
      }
    }
  }
`;
