// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const AGGREGATE_USER = gql`
  query AggregateUser($filter: UserFilter) {
    aggregateUser(filter: $filter) {
      count
      nameMin
      nameMax
      githubMin
      githubMax
      emailMin
      emailMax
      telegramMin
      telegramMax
      rateMin
      rateMax
      rateSum
      rateAvg
    }
  }
`;
