// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const AGGREGATE_SOLUTION = gql`
  query AggregateSolution($filter: SolutionFilter) {
    aggregateSolution(filter: $filter) {
      count
      urlMin
      urlMax
      descriptionMin
      descriptionMax
      costUSDMin
      costUSDMax
      costUSDSum
      costUSDAvg
      created_atMin
      created_atMax
      updated_atMin
      updated_atMax
    }
  }
`;
