// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const GET_SOLUTION = gql`
  query GetSolution($id: ID!) {
    getSolution(id: $id) {
      id
      creator {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      url
      description
      costUSD
      created_at
      updated_at
      problem {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      introducedProblems {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      introducedProblemsAggregate {
        count
        titleMin
        titleMax
        shortDescriptionMin
        shortDescriptionMax
        detailedDescriptionMin
        detailedDescriptionMax
        claimedAtMin
        claimedAtMax
        created_atMin
        created_atMax
        updated_atMin
        updated_atMax
      }
    }
  }
`;
