// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { gql } from '@apollo/client';

export const QUERY_SOLUTION = gql`
  query QuerySolution(
    $filter: SolutionFilter
    $order: SolutionOrder
    $first: Int
    $offset: Int
  ) {
    querySolution(
      filter: $filter
      order: $order
      first: $first
      offset: $offset
    ) {
      id
      creator {
        name
        github
        email
        telegram
        rate
        actionHistory
      }
      url
      description
      costUSD
      created_at
      updated_at
      problem {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      introducedProblems {
        id
        title
        shortDescription
        detailedDescription
        status
        claimedAt
        requiredSkills
        created_at
        updated_at
      }
      introducedProblemsAggregate {
        count
        titleMin
        titleMax
        shortDescriptionMin
        shortDescriptionMax
        detailedDescriptionMin
        detailedDescriptionMax
        claimedAtMin
        claimedAtMax
        created_atMin
        created_atMax
        updated_atMin
        updated_atMax
      }
    }
  }
`;
