name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./webapp

      - name: Build the project
        run: pnpm run build
        working-directory: ./webapp

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp/dist

  tag:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new tag
        id: tag
        run: |
          TAG_NAME=$(date +'%Y%m%d%H%M%S')
          git tag $TAG_NAME
          git push origin $TAG_NAME
        working-directory: ./webapp