name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "webapp/**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp

      - name: Build the project
        run: yarn build
        working-directory: ./webapp

      - name: Create fallback 404 page
        run: cp dist/index.html dist/404.html
        working-directory: ./webapp

      - name: Config GitHub Pages
        uses: actions/configure-pages@v5
        id: pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./webapp/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  tag:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new tag
        id: tag
        run: |
          TAG_NAME=$(date +'%Y%m%d%H%M%S')
          git tag $TAG_NAME
          git push origin $TAG_NAME
        working-directory: ./webapp
