name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "webapp/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp

      - name: Build the project
        run: yarn build
        working-directory: ./webapp

      - name: Config GitHub Pages
        uses: actions/configure-pages@v2
        id: pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./webapp/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment

  tag:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new tag
        id: tag
        run: |
          TAG_NAME=$(date +'%Y%m%d%H%M%S')
          git tag $TAG_NAME
          git push origin $TAG_NAME
        working-directory: ./webapp
